### ISSUE TITLE
hosts in @kowith337/PersonalFilterlistCollection

### ISSUE THREAD

**Issue by kowith337** [dead-hosts/dev-center#1]
**Is your list in a Git repository? List them here**

* Repository Name: PersonalFilterlistCollection
  * repository link: https://github.com/kowith337/PersonalFilterListCollection
  * Lists to test:
    * https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_facebook0.txt
    * https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_google_adservice_id.txt

**Comment by funilrys** [comment]
Hi @kowith337, 
Just included the lists into our infrastructure.

Please follow https://github.com/dead-hosts in order to join the team so that you can administrate the created repositories.

Have a nice day/night.

Cheers,
