### ISSUE TITLE
cjxlist

### ISSUE THREAD

**Issue by cjx82630** [dead-hosts/dev-center#16]
**Is your list in a Git repository? List them here**

* Repository Name
cjxlist
  * repository link
https://github.com/cjx82630/cjxlist
  * Lists to test:
https://raw.githubusercontent.com/cjx82630/cjxlist/master/adsChina.txt

**Comment by funilrys** [comment]
Hey @cjx82630, sorry for the waiting time. 

Should I add your list ?

Let me know as I'm going to schedule some new addition.

**Comment by cjx82630** [comment]
Thanks for your reply. No need to add my list. I found that using batch processing to query whois has met my expectations.

**Comment by funilrys** [comment]
Great! Let me know if you change your mind as PyFunceble do more than just WHOIS :smile_cat: 

Stay safe and healthy!
