### ISSUE TITLE
Zelo72s Domain-Blocklists

### ISSUE THREAD

**Issue by ghost** [dead-hosts/dev-center#19]
* Repository Name: RPI
  * https://github.com/Zelo72/rpi
  * Lists to test:
    * https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/multi.txt
    * https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/fake.txt

**Comment by funilrys** [comment]
Sorry, that I didn't saw this earlier ... It got lost in my flood of notifications... 

Do you still want it ?

**Comment by ghost** [comment]
Yes, thanks.
