### ISSUE TITLE
Red Flag Domains

### ISSUE THREAD

**Issue by smed79** [dead-hosts/dev-center#26]
![red-flag](https://i25.servimg.com/u/f25/11/94/21/24/red-fl10.png)

* Red Flag Domains
  * Recently registered probably malicious domain names in french TLDs
  * https://dl.red.flag.domains/red.flag.domains.txt

---

- [x] https://github.com/dead-hosts/Red-Flag-Domains_web_red.flag.domains

**Comment by funilrys** [comment]
Repository Created, Invitation sent to you. Closing
