### ISSUE TITLE
ABPindo - supplement for Easylist

### ISSUE THREAD

**Issue by gmarcher** [dead-hosts/dev-center#6]
**Is your list in a Git repository? List them here**

* ABPindo
  * https://github.com/ABPindo/indonesianadblockrules
  * Lists to test:
    * https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt

regards,
ABPindo team

**Comment by funilrys** [comment]
Invitation to join @dead-hosts sent to you.

Closing as it is now integrated.

**Comment by gmarcher** [comment]
want to ask,
if i want change to this filter `https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/tools/validatehost/host.txt` do i need make new request or only edit my info.json ? i want to add support for host file

**Comment by funilrys** [comment]
Hi @gmarcher,

If you want to replace the other one, you can simply update the `info.json` file. Otherwise, let me know, I will create and configure a new repository for it.

Stay safe and healthy.
Nissar

**Comment by gmarcher** [comment]
nice, thanks. please create and configure new repository for me

**Is your list in a Git repository? List them here**

* ABPindo
  * https://github.com/ABPindo/indonesianadblockrules
  * Lists to test:
    * https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt
    * https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/tools/validatehost/host.txt

regards,
ABPindo team

**Comment by funilrys** [comment]
Note to self: Schedule this (on top) in the next 24/48h (Berlin Time).

Sorry for the waiting time @gmarcher.

Stay safe and healthy.
Nissar
